
(function(){
  'use strict';
  var VERSION='29.0.0';
  var CURRENCY='₽LC';
  var SAVE_KEY='cs2_case_lab_save_v29_stable';
  var OLD_KEYS=['cs2_case_lab_save','cs2_case_lab_state','cs2_case_lab_v8_state','cs2_case_lab_v7_state','cs2_case_lab_v6_state','cs2_case_lab_v5_state'];
  var BALANCE_START=15000;
  var HERO_AK='https://cdn.csgoskins.gg/public/uih/products/aHR0cHM6Ly9jZG4uY3Nnb3NraW5zLmdnL3B1YmxpYy9pbWFnZXMvYnVja2V0cy9lY29uL2RlZmF1bHRfZ2VuZXJhdGVkL3dlYXBvbl9hazQ3X2N1X2FrNDdfY29icmFfbGlnaHQuZjQ1OGMxMDVhYjc1ZmM3NGU4ZGVjMTlhZDU4YmJlZTkwNzJhMTE1YS5wbmc-/auto/auto/85/notrim/512a8c5e2da478fafdbd7648d0ccf5ba.webp';
  var HERO_AWP='https://cdn.csgoskins.gg/public/uih/products/aHR0cHM6Ly9jZG4uY3Nnb3NraW5zLmdnL3B1YmxpYy9pbWFnZXMvYnVja2V0cy9lY29uL2RlZmF1bHRfZ2VuZXJhdGVkL3dlYXBvbl9hd3BfY3VfYXdwX2h5cGVyX2JlYXN0X2xpZ2h0Ljk1YWRjNTkyNTc5ZTJkYjNlMmZjNzU4MDkxZjU0MGM4ZWY2NGY1ZTYucG5n/auto/auto/85/notrim/526d33d62002109270055c4d9d65e9d0.webp';
  var HERO_KNIFE='https://cdn.csgoskins.gg/public/uih/products/aHR0cHM6Ly9jZG4uY3Nnb3NraW5zLmdnL3B1YmxpYy9pbWFnZXMvYnVja2V0cy9lY29uL2RlZmF1bHRfZ2VuZXJhdGVkL3dlYXBvbl9rbmlmZV9rYXJhbWJpdF9hbV9kb3BwbGVyX3BoYXNlMV9saWdodC4yYjdjYWFhMmE5OGRiNmY2NWU1MWJiMmQ5YThlNzA0MDhkNjAwOWE3LnBuZw--/auto/auto/85/notrim/bde86cbbe92dc9a7671a61764d6d82dd.webp';
  var CASE_IMG={
    kilo:'https://cdn.jsdelivr.net/gh/ByMykel/counter-strike-image-tracker@main/static/panorama/images/econ/weapon_cases/crate_community_33_png.png',
    rev:'https://cdn.jsdelivr.net/gh/ByMykel/counter-strike-image-tracker@main/static/panorama/images/econ/weapon_cases/crate_community_31_png.png',
    recoil:'https://cdn.jsdelivr.net/gh/ByMykel/counter-strike-image-tracker@main/static/panorama/images/econ/weapon_cases/crate_community_30_png.png',
    dreams:'https://cdn.jsdelivr.net/gh/ByMykel/counter-strike-image-tracker@main/static/panorama/images/econ/weapon_cases/crate_community_29_png.png',
    snake:'https://cdn.jsdelivr.net/gh/ByMykel/counter-strike-image-tracker@main/static/panorama/images/econ/weapon_cases/crate_community_27_png.png',
    clutch:'https://cdn.jsdelivr.net/gh/ByMykel/counter-strike-image-tracker@main/static/panorama/images/econ/weapon_cases/crate_community_17_png.png'
  };
  function $(s,r){return (r||document).querySelector(s)}
  function $$(s,r){return Array.prototype.slice.call((r||document).querySelectorAll(s))}
  function esc(v){return String(v==null?'':v).replace(/[&<>'"]/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]})}
  function fmt(n){n=Math.round(Number(n)||0);return n.toLocaleString('ru-RU')+' '+CURRENCY}
  function rnd(){try{var a=new Uint32Array(1);crypto.getRandomValues(a);return a[0]/4294967296}catch(e){return Math.random()}}
  function id(){return 'i'+Date.now().toString(36)+Math.floor(rnd()*1e9).toString(36)}
  function svgSkin(name,c1,c2){c1=c1||'#60a5fa';c2=c2||'#f97316';return 'data:image/svg+xml;charset=UTF-8,'+encodeURIComponent('<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 760 360"><defs><linearGradient id="g" x1="0" x2="1"><stop stop-color="'+c1+'"/><stop offset=".55" stop-color="#8b5cf6"/><stop offset="1" stop-color="'+c2+'"/></linearGradient></defs><rect width="760" height="360" rx="38" fill="#111827"/><path d="M80 170h380l40-45h120c35 0 65 22 80 55l26 62h-98l-16-35H508l-58 62h-90l60-68H180l-45 48H52l45-58H76c-32 0-32-21 4-21z" fill="url(#g)"/><path d="M150 125h230l38-48h94l-40 48h140c32 0 50 16 62 40H110c6-24 18-40 40-40z" fill="#e5e7eb" opacity=".22"/><text x="380" y="60" fill="#fff" font-family="Arial" font-size="32" font-weight="900" text-anchor="middle">'+esc(name)+'</text></svg>')}
  function makeItem(idv,name,rarity,value,img,c1,c2){return {id:idv,name:name,displayName:name,rarity:rarity,value:value,image:img||svgSkin(name,c1,c2),rarityColor:rarityColor(rarity),weight:rarityWeight(rarity)}}
  function rarityColor(r){return {'Consumer Grade':'#b0c3d9','Industrial Grade':'#5e98d9','Mil-Spec Grade':'#4b69ff','Restricted':'#8847ff','Classified':'#d32ce6','Covert':'#eb4b4b','Exceedingly Rare':'#ffd700','Extraordinary':'#e4ae33','High Grade':'#4b69ff','Remarkable':'#8847ff','Exotic':'#d32ce6','Master':'#eb4b4b'}[r]||'#60a5fa'}
  function rarityWeight(r){return {'Consumer Grade':80,'Industrial Grade':60,'Mil-Spec Grade':45,'Restricted':16,'Classified':6,'Covert':2.2,'Exceedingly Rare':0.45,'Extraordinary':0.6,'High Grade':35,'Remarkable':12,'Exotic':4,'Master':1.2}[r]||8}
  var items=[
    makeItem('ak_redline','AK-47 | Redline','Classified',2700,HERO_AK),
    makeItem('awp_hyper','AWP | Hyper Beast','Covert',6900,HERO_AWP),
    makeItem('karambit_doppler','★ Karambit | Doppler','Exceedingly Rare',52000,HERO_KNIFE),
    makeItem('ak_vulcan','AK-47 | Vulcan','Covert',18500,null,'#38bdf8','#2563eb'),
    makeItem('m4_print','M4A1-S | Printstream','Covert',8800,null,'#f8fafc','#a855f7'),
    makeItem('awp_asiimov','AWP | Asiimov','Covert',11800,null,'#f97316','#f8fafc'),
    makeItem('usp_kill','USP-S | Kill Confirmed','Covert',3300,null,'#ef4444','#f8fafc'),
    makeItem('glock_water','Glock-18 | Water Elemental','Classified',920,null,'#38bdf8','#ef4444'),
    makeItem('mp9_food','MP9 | Food Chain','Classified',900,null,'#84cc16','#ec4899'),
    makeItem('mac_neon','MAC-10 | Neon Rider','Covert',1800,null,'#ec4899','#22d3ee'),
    makeItem('tec_isaac','Tec-9 | Isaac','Mil-Spec Grade',190,null,'#ef4444','#f97316'),
    makeItem('p90_death','P90 | Death Grip','Restricted',420,null,'#94a3b8','#ef4444'),
    makeItem('ssg_fever','SSG 08 | Fever Dream','Restricted',380,null,'#a855f7','#f472b6'),
    makeItem('p250_asiimov','P250 | Asiimov','Classified',780,null,'#f97316','#f8fafc'),
    makeItem('gloves_vice','★ Sport Gloves | Vice','Extraordinary',47000,null,'#f472b6','#8b5cf6'),
    makeItem('knife_butterfly','★ Butterfly Knife | Doppler','Exceedingly Rare',65000,null,'#22d3ee','#a855f7')
  ];
  function c(idv,name,price,img,pool,kind){return {id:idv,name:name,price:price,image:img,items:pool||items,kind:kind||'case',source:'Steam-like ₽LC'}}
  var cases=[
    c('kilowatt','Kilowatt Case',840,CASE_IMG.kilo,items.slice(0,13).concat(items.slice(14,16))),
    c('revolution','Revolution Case',501,CASE_IMG.rev,items.slice(2,15)),
    c('recoil','Recoil Case',720,CASE_IMG.recoil,items.slice(4,16)),
    c('dreams','Dreams & Nightmares Case',650,CASE_IMG.dreams,items.slice(1,14).concat([items[15]])),
    c('snakebite','Snakebite Case',460,CASE_IMG.snake,items.slice(7,14)),
    c('clutch','Clutch Case',620,CASE_IMG.clutch,items.slice(0,12).concat([items[14]])),
    c('red','Red Covert Case',3200,svgSkin('RED CASE','#ef4444','#7f1d1d'),items.filter(function(x){return x.rarity==='Covert'}),'special'),
    c('knife','Knife Case',18000,svgSkin('KNIFE','#ffd166','#8b5cf6'),items.filter(function(x){return x.name.charAt(0)==='★' && x.rarity==='Exceedingly Rare'}),'special'),
    c('gloves','Gloves Case',16000,svgSkin('GLOVES','#ffd166','#22c55e'),items.filter(function(x){return x.rarity==='Extraordinary'}),'special'),
    c('sticker','Tournament Stickers',300,svgSkin('STICKERS','#facc15','#60a5fa'),[
      makeItem('st1','Sticker | NAVI | Copenhagen 2024','High Grade',120),makeItem('st2','Sticker | Team Spirit | Shanghai 2024','Remarkable',360),makeItem('st3','Sticker | G2 | Austin 2025','Exotic',900)
    ],'special')
  ];
  var promo={WELCOME29:5000,EFIMDROP:7500,IOSLAB:3000,FASTOPEN:2500,BATTLEFIX:6000,RUBLELC:10000,CASEKING:15000,GREENLUCK:4000,REDHUNT:8000,KNIFEDREAM:25000,ARMORYPASS:12000,STICKER2026:2000,DAILYBOOST:1500,MEGALAB:50000,TEST100K:100000};
  var state=load();
  var currentCase=null;
  function def(){return {version:VERSION,balance:BALANCE_START,inventory:[],opened:0,earned:0,spent:0,sold:0,upgrades:0,contracts:0,battles:0,wins:0,usedPromos:[],lastWheelAt:0,tx:[]}}
  function load(){var s=null;try{s=JSON.parse(localStorage.getItem(SAVE_KEY)||'null')}catch(e){} if(!s){s=def()} if(!s.inventory)s.inventory=[]; if(!s.usedPromos)s.usedPromos=[]; if(!s.tx)s.tx=[]; if(!Number(s.balance)&&s.opened===0&&s.inventory.length===0)s.balance=BALANCE_START; return s}
  function save(){try{localStorage.setItem(SAVE_KEY,JSON.stringify(state));}catch(e){try{sessionStorage.setItem(SAVE_KEY,JSON.stringify(state));}catch(x){}}}
  function tx(text,amount){state.tx.unshift({text:text,amount:Math.round(amount),time:new Date().toLocaleString('ru-RU')});state.tx=state.tx.slice(0,30)}
  function earn(n,text){n=Math.round(Number(n)||0);state.balance+=n;state.earned+=n;tx(text||'Начисление',n);save();renderGlobals()}
  function spend(n,text){n=Math.round(Number(n)||0);if(state.balance<n){toast('Недостаточно средств: нужно '+fmt(n),'bad');return false}state.balance-=n;state.spent+=n;tx(text||'Списание',-n);save();renderGlobals();return true}
  function addItem(base,source){var wear=['Factory New','Minimal Wear','Field-Tested','Well-Worn','Battle-Scarred'][Math.floor(rnd()*5)];var mult={ 'Factory New':1.35,'Minimal Wear':1.12,'Field-Tested':.94,'Well-Worn':.78,'Battle-Scarred':.64}[wear];var it={uid:id(),id:base.id,name:base.name,displayName:base.name,rarity:base.rarity,rarityColor:base.rarityColor,value:Math.max(1,Math.round(base.value*mult*(.88+rnd()*.28))),image:base.image,wear:wear,source:source||'drop',addedAt:Date.now()};state.inventory.unshift(it);state.opened+=0;save();renderGlobals();return it}
  function weighted(ca){var pool=ca.items||items,total=0,i,w=[],x;for(i=0;i<pool.length;i++){x=pool[i];var ratio=x.value/(ca.price||1);var ww=x.weight||8;if(ratio>1)ww*=.45;if(ratio>2)ww*=.22;if(ratio<.6)ww*=1.35;w.push(ww);total+=ww}var r=rnd()*total;for(i=0;i<pool.length;i++){r-=w[i];if(r<=0)return pool[i]}return pool[pool.length-1]}
  function renderGlobals(){var bs=$$('.js-balance');for(var i=0;i<bs.length;i++)bs[i].textContent=fmt(state.balance);var cs=$$('.js-inv-count');for(i=0;i<cs.length;i++)cs[i].textContent=state.inventory.length;var vs=$$('.js-version');for(i=0;i<vs.length;i++)vs[i].textContent='29'}
  function setActive(){var p=document.body.getAttribute('data-page')||'home';var map={home:'index',promos:'promo'};var key=map[p]||p;var links=$$('.navlinks a');for(var i=0;i<links.length;i++){links[i].className=links[i].href.indexOf(key+'.html')>-1?'active':''}}
  function caseVisual(ca){return '<div class="case-visual classic-case"><img class="case-img" src="'+esc(ca.image)+'" onerror="this.src=\''+svgSkin(ca.name)+'\'" alt="'+esc(ca.name)+'"></div>'}
  function caseCard(ca){return '<article class="case-card"><span class="case-kind">Кейс</span><span class="price-tier">'+(ca.price<700?'дешёвый':ca.price>5000?'дорогой':'средний')+'</span>'+caseVisual(ca)+'<h3>'+esc(ca.name)+'</h3><div class="case-meta"><span>'+ca.items.length+' предметов</span><b>'+fmt(ca.price)+'</b></div><div class="mini-list"><span class="pill">Mil-Spec Grade</span><span class="pill">Restricted</span><span class="pill">Classified</span><span class="pill">Covert</span></div><small class="source">'+esc(ca.source)+'</small><div class="case-actions"><button class="btn primary" data-open-case="'+ca.id+'">Крутить</button><button class="btn" data-view-case="'+ca.id+'">Пул</button></div></article>'}
  function itemCard(it,buttons){return '<article class="item-card" style="--rar:'+(it.rarityColor||'#60a5fa')+'"><div class="item-art"><img src="'+esc(it.image)+'" onerror="this.src=\''+svgSkin(it.name)+'\'" alt="'+esc(it.name)+'"></div><h4>'+esc(it.displayName||it.name)+'</h4><small>'+esc(it.rarity)+' '+(it.wear?'· '+esc(it.wear):'')+'</small><div class="value-row"><b>'+fmt(it.value)+'</b></div>'+(buttons||'')+'</article>'}
  function route(){setActive();renderGlobals();var p=document.body.getAttribute('data-page')||'home';if(p==='home')renderHome();else if(p==='cases')renderCases();else if(p==='inventory')renderInventory();else if(p==='upgrade')renderUpgrade();else if(p==='contracts')renderContracts();else if(p==='wheel')renderWheel();else if(p==='battle')renderBattle();else if(p==='ads')renderAds();else if(p==='promos')renderPromos();else if(p==='profile')renderProfile();else if(p==='install')renderInstall();wireActions()}
  function renderHome(){var r=$('#homeRoot');if(!r)return;r.innerHTML=stats()+'<section class="block"><div class="head"><div><h2>Популярные кейсы</h2><p>Кнопка «Крутить» сразу открывает модальное окно, списывает баланс и запускает рулетку.</p></div><a class="btn primary" href="cases.html">Все кейсы</a></div><div class="grid case-grid">'+cases.slice(0,6).map(caseCard).join('')+'</div></section><section class="block"><div class="head"><div><h2>Редкие дропы</h2></div></div><div class="grid item-grid">'+items.slice(0,8).map(function(x){return itemCard(x,'')}).join('')+'</div></section>'}
  function stats(){return '<div class="grid cards-4"><div class="stat"><small>Баланс</small><b>'+fmt(state.balance)+'</b></div><div class="stat"><small>Предметов</small><b>'+state.inventory.length+'</b></div><div class="stat"><small>Открыто кейсов</small><b>'+state.opened+'</b></div><div class="stat"><small>Заработано</small><b>'+fmt(state.earned)+'</b></div></div>'}
  function renderCases(){var r=$('#casesRoot');if(!r)return;r.innerHTML='<div class="notice"><b>Каталог готов.</b> Все механики работают локально на GitHub Pages.</div><section class="block"><div class="head"><h2>Кейсы</h2><p>'+cases.length+' шт.</p></div><div class="case-grid grid">'+cases.map(caseCard).join('')+'</div></section>'}
  function renderInventory(){var r=$('#inventoryRoot');if(!r)return;var total=state.inventory.reduce(function(s,x){return s+(Number(x.value)||0)},0);r.innerHTML='<div class="notice"><b>Сумма инвентаря:</b> '+fmt(total)+' <button class="btn red" data-action="sell-all" style="margin-left:10px">Продать всё</button></div>'+(state.inventory.length?'<div class="grid item-grid">'+state.inventory.map(function(x){return itemCard(x,'<div class="item-actions"><button data-sell="'+x.uid+'">Продать</button><button data-upgrade-item="'+x.uid+'">Апгрейд</button><button data-contract-item="'+x.uid+'">Контракт</button></div>')}).join('')+'</div>':'<div class="empty">Инвентарь пуст. Открой кейс, выиграй battle или прокрути колесо.</div>')}
  function renderUpgrade(){var r=$('#upgradeRoot');if(!r)return;var opts=state.inventory.map(function(x){return '<option value="'+x.uid+'">'+esc(x.displayName)+' · '+fmt(x.value)+'</option>'}).join('');r.innerHTML=state.inventory.length?'<div class="upgrade-layout"><aside class="panel"><h3>Твой предмет</h3><select id="upItem">'+opts+'</select><h3>Цель</h3><select id="upTarget">'+items.filter(function(x){return x.value>500}).map(function(x){return '<option value="'+x.id+'">'+esc(x.name)+' · '+fmt(x.value)+'</option>'}).join('')+'</select><button class="btn primary huge" data-action="do-upgrade">Апгрейд</button><p class="small">При проигрыше предмет исчезает.</p></aside><section class="panel"><div class="upgrade-roulette"><div class="upgrade-lane"><span class="zone win">WIN</span><span class="zone lose">LOSE</span></div></div></section></div>':'<div class="empty">Нет предметов для апгрейда.</div>'}
  function renderContracts(){var r=$('#contractsRoot');if(!r)return;var selected=state.contractSelected||[];r.innerHTML='<div class="notice">Выбрано: <b>'+selected.length+'</b> / 3-10 <button class="btn primary" data-action="do-contract">Создать контракт</button> <button class="btn" data-action="clear-contract">Очистить</button></div>'+(state.inventory.length?'<div class="grid item-grid">'+state.inventory.map(function(x){var sel=selected.indexOf(x.uid)>-1;return '<article class="item-card '+(sel?'selected':'')+'" style="--rar:'+x.rarityColor+'"><div class="item-art"><img src="'+esc(x.image)+'"></div><h4>'+esc(x.displayName)+'</h4><small>'+esc(x.rarity)+'</small><div class="value-row"><b>'+fmt(x.value)+'</b></div><div class="item-actions"><button data-contract-item="'+x.uid+'">'+(sel?'Убрать':'Выбрать')+'</button></div></article>'}).join('')+'</div>':'<div class="empty">Нет предметов для контракта.</div>')}
  function renderWheel(){var r=$('#wheelRoot');if(!r)return;var left=Math.max(0,(state.lastWheelAt||0)+7200000-Date.now());r.innerHTML='<div class="wheel-pointer"></div><div class="wheel" id="bonusWheel"><span>LAB</span></div><button class="btn primary huge" data-action="spin-wheel" '+(left?'disabled':'')+'>'+(left?'Доступно через '+Math.ceil(left/60000)+' мин':'Крутить бонусное колесо')+'</button><div class="wheel-result empty" id="wheelResult">Колесо выдаёт ₽LC или предмет.</div>'}
  function renderBattle(){var r=$('#battleRoot');if(!r)return;r.innerHTML='<div class="battle-layout"><aside class="panel"><h3>Case Battle</h3><select id="battleCase">'+cases.slice(0,6).map(function(x){return '<option value="'+x.id+'">'+x.name+' · '+fmt(x.price)+'</option>'}).join('')+'</select><button class="btn primary huge" data-action="start-battle">Начать баттл</button></aside><section class="panel" id="battleArena"><div class="empty">Выбери кейс и начни battle.</div></section></div>'}
  function renderAds(){var r=$('#adsRoot');if(!r)return;r.innerHTML='<div class="ad-card"><div><p class="kicker">Реклама своих проектов</p><h2>10 секунд просмотра = 750 ₽LC</h2><button class="btn primary huge" data-action="watch-ad">Смотреть рекламу</button><div class="progress"><span id="adProgress"></span></div><p id="adStatus">Готово к просмотру.</p></div><div class="project-grid"><div class="project-card"><h3>Портфолио</h3><p>Сайт-визитка и проекты</p></div><div class="project-card"><h3>YouTube</h3><p>Видео и конференции</p></div><div class="project-card"><h3>GitHub</h3><p>HTML-проекты</p></div><div class="project-card"><h3>Подкаст</h3><p>Финансы и учебные задания</p></div></div></div>'}
  function renderPromos(){var r=$('#promosRoot');if(!r)return;r.innerHTML='<div class="panel"><h3>Введи промокод</h3><div class="form-row"><input id="promoInput" placeholder="Например WELCOME29"><button class="btn primary" data-action="use-promo">Активировать</button></div><p class="small">Код активируется один раз.</p></div>'}
  function renderProfile(){var r=$('#profileRoot');if(!r)return;var total=state.inventory.reduce(function(s,x){return s+(Number(x.value)||0)},0);r.innerHTML=stats()+'<section class="block"><div class="grid cards-3"><div class="panel"><h3>Сохранение</h3><p>Версия: '+VERSION+'</p><button class="btn" data-action="export-save">Экспорт</button> <button class="btn" data-action="import-save">Импорт</button><textarea id="saveBox" placeholder="Тут появится или сюда вставляется save"></textarea></div><div class="panel danger"><h3>Сброс</h3><button class="btn red" data-action="reset-progress">Сбросить прогресс</button><button class="btn" data-action="add-debug-coins">+10 000 ₽LC</button></div><div class="panel"><h3>Инвентарь</h3><p>Стоимость: <b>'+fmt(total)+'</b></p></div></div></section><section class="block"><h2>История баланса</h2><div class="tx-list">'+(state.tx.length?state.tx.map(function(t){return '<div class="tx"><span>'+esc(t.text)+'<small>'+esc(t.time)+'</small></span><b class="'+(t.amount>=0?'plus':'minus')+'">'+(t.amount>=0?'+':'')+fmt(t.amount)+'</b></div>'}).join(''):'<div class="empty">История пуста.</div>')+'</div></section>'}
  function renderInstall(){var r=$('#installRoot');if(!r)return;r.innerHTML='<div class="panel"><h2>Установка</h2><p>На iPhone: Safari → Поделиться → На экран Домой.</p><a class="btn primary" href="download/cs2-case-lab-windows.zip">Скачать ZIP для Windows</a></div>'}
  function openCaseModal(caseId,spin){var ca=findCase(caseId);if(!ca)return;currentCase=caseId;$('#caseModalTitle').textContent=ca.name;$('#caseModalBody').innerHTML='<div class="case-open-layout"><aside class="open-aside">'+caseVisual(ca)+'<div class="notice">Цена открытия: <b>'+fmt(ca.price)+'</b></div><button class="btn primary huge" data-action="spin-current-case">Открыть 1x за '+fmt(ca.price)+'</button><button class="btn blue huge" data-action="spin-fast">Открыть быстро 1x</button><div class="multi-open-row"><button class="small-btn" data-action="open-multi" data-count="3">Быстро x3</button><button class="small-btn" data-action="open-multi" data-count="5">Быстро x5</button><button class="small-btn" data-action="open-multi" data-count="10">Быстро x10</button></div></aside><section class="case-main"><div class="roulette-box"><div class="roulette-pointer"></div><div class="roulette-strip" id="rouletteStrip">'+rollCards(ca,20)+'</div></div><h3>Содержимое кейса</h3><div class="case-contents">'+ca.items.map(function(x){return itemCard(x,'')}).join('')+'</div></section></div>';openModal('#caseModal');if(spin)setTimeout(function(){spinCase(caseId,{})},80);wireActions()}
  function rollCards(ca,n){var s='',i;for(i=0;i<n;i++)s+='<div class="roll-card" style="--rar:'+weighted(ca).rarityColor+'"><img src="'+esc(weighted(ca).image)+'"><b>'+esc(weighted(ca).name)+'</b></div>';return s}
  function spinCase(caseId,opt){var ca=findCase(caseId);if(!ca)return;var count=(opt&&opt.count)||1;var fast=opt&&opt.fast;var cost=ca.price*count;if(!spend(cost,'Открытие '+ca.name+(count>1?' x'+count:'')))return;state.opened+=count;save();if(fast||count>1){var drops=[];for(var i=0;i<count;i++)drops.push(addItem(weighted(ca),ca.name));showBatch(drops,cost);return}var win=weighted(ca),strip=$('#rouletteStrip');if(strip){strip.innerHTML=rollCards(ca,35)+'<div class="roll-card" style="--rar:'+win.rarityColor+'"><img src="'+esc(win.image)+'"><b>'+esc(win.name)+'</b></div>'+rollCards(ca,8);strip.style.transition='none';strip.style.transform='translateX(0)';setTimeout(function(){strip.style.transition='transform 3s cubic-bezier(.08,.75,.08,1)';strip.style.transform='translateX(-4200px)'},30)}setTimeout(function(){showDrop(addItem(win,ca.name))},fast?10:3200)}
  function showDrop(it){$('#dropModalBody').innerHTML='<div class="drop-box"><p class="kicker">Выпал предмет</p><img class="drop-img" src="'+esc(it.image)+'"><h2 style="color:'+it.rarityColor+'">'+esc(it.displayName)+'</h2><p>'+esc(it.rarity)+' · '+esc(it.wear)+'</p><h3>'+fmt(it.value)+'</h3><div class="drop-actions"><button class="btn green" data-sell="'+it.uid+'">Продать</button><button class="btn" data-close-modal>Оставить</button><button class="btn primary" data-action="open-again">Открыть ещё</button></div></div>';openModal('#dropModal');wireActions()}
  function showBatch(arr,cost){var total=arr.reduce(function(s,x){return s+x.value},0);$('#dropModalBody').innerHTML='<div class="drop-box"><h2>Массовое открытие x'+arr.length+'</h2><p>Потрачено '+fmt(cost)+' · Выпало на '+fmt(total)+'</p><div class="grid item-grid">'+arr.map(function(x){return itemCard(x,'')}).join('')+'</div><div class="drop-actions"><button class="btn green" data-action="sell-batch" data-uids="'+arr.map(function(x){return x.uid}).join(',')+'">Продать всё</button><button class="btn" data-close-modal>Оставить</button></div></div>';openModal('#dropModal');wireActions()}
  function openModal(sel){var m=$(sel);if(m){m.classList.add('show');m.style.display='flex';m.style.pointerEvents='auto'}}
  function closeModal(sel){var m=typeof sel==='string'?$(sel):sel;if(m){m.classList.remove('show');m.style.display='none';m.style.pointerEvents='none'}}
  function findCase(idv){for(var i=0;i<cases.length;i++)if(cases[i].id===idv)return cases[i];return null}
  function findInv(uid){for(var i=0;i<state.inventory.length;i++)if(state.inventory[i].uid===uid)return state.inventory[i];return null}
  function sell(uid){var it=findInv(uid);if(!it)return;state.inventory=state.inventory.filter(function(x){return x.uid!==uid});state.sold+=it.value;earn(it.value,'Продажа '+it.displayName);route();toast('Продано за '+fmt(it.value),'good')}
  function action(el,ev){if(!el)return false;if(ev){ev.preventDefault();ev.stopPropagation()}var a=el.getAttribute('data-action');if(el.getAttribute('data-open-case')){openCaseModal(el.getAttribute('data-open-case'),true);return true}if(el.getAttribute('data-view-case')){openCaseModal(el.getAttribute('data-view-case'),false);return true}if(el.getAttribute('data-sell')){sell(el.getAttribute('data-sell'));return true}if(el.getAttribute('data-close-modal')!==null){closeModal(el.closest('.modal'));return true}if(el.getAttribute('data-upgrade-item')){location.href='upgrade.html';return true}if(el.getAttribute('data-contract-item')){var u=el.getAttribute('data-contract-item');state.contractSelected=state.contractSelected||[];var idx=state.contractSelected.indexOf(u);if(idx>-1)state.contractSelected.splice(idx,1);else if(state.contractSelected.length<10)state.contractSelected.push(u);save();route();return true}if(a==='spin-current-case'){spinCase(currentCase,{});return true}if(a==='spin-fast'){spinCase(currentCase,{fast:true});return true}if(a==='open-again'){closeModal('#dropModal');openCaseModal(currentCase,true);return true}if(a==='open-multi'){spinCase(currentCase,{fast:true,count:Number(el.getAttribute('data-count'))||3});return true}if(a==='sell-batch'){var ids=(el.getAttribute('data-uids')||'').split(',');var total=0;for(var i=0;i<ids.length;i++){var it=findInv(ids[i]);if(it){total+=it.value;state.inventory=state.inventory.filter(function(x){return x.uid!==it.uid})}}earn(total,'Массовая продажа');closeModal('#dropModal');route();return true}if(a==='sell-all'){var sum=state.inventory.reduce(function(s,x){return s+x.value},0);state.inventory=[];earn(sum,'Продажа всего инвентаря');route();return true}if(a==='spin-wheel'){spinWheel();return true}if(a==='watch-ad'){watchAd();return true}if(a==='use-promo'){usePromo();return true}if(a==='do-upgrade'){doUpgrade();return true}if(a==='do-contract'){doContract();return true}if(a==='clear-contract'){state.contractSelected=[];save();route();return true}if(a==='start-battle'){startBattle();return true}if(a==='add-debug-coins'){earn(10000,'Тестовое начисление');return true}if(a==='reset-progress'){if(confirm('Сбросить прогресс?')){state=def();save();route()}return true}if(a==='export-save'){var b=$('#saveBox');if(b)b.value=btoa(unescape(encodeURIComponent(JSON.stringify(state))));return true}if(a==='import-save'){var bx=$('#saveBox');try{state=JSON.parse(decodeURIComponent(escape(atob(bx.value.trim()))));save();route()}catch(e){toast('Не удалось импортировать','bad')}return true}return false}
  function spinWheel(){var left=(state.lastWheelAt||0)+7200000-Date.now();if(left>0){toast('Колесо будет доступно позже','warn');return}state.lastWheelAt=Date.now();var w=$('#bonusWheel');if(w)w.style.transform='rotate('+(900+Math.floor(rnd()*720))+'deg)';setTimeout(function(){if(rnd()<.72){var n=[300,500,750,1000,1500,2500][Math.floor(rnd()*6)];earn(n,'Колесо бонусов');$('#wheelResult').innerHTML='Выпало: <b>'+fmt(n)+'</b>'}else{var it=addItem(items[Math.floor(rnd()*items.length)],'wheel');$('#wheelResult').innerHTML='Выпал предмет: <b>'+esc(it.displayName)+'</b>'}renderWheel();},1200)}
  function watchAd(){var p=$('#adProgress'),s=$('#adStatus'),i=0;if(s)s.textContent='Просмотр рекламы...';var t=setInterval(function(){i++;if(p)p.style.width=(i*10)+'%';if(i>=10){clearInterval(t);earn(750,'Просмотр рекламы');if(s)s.textContent='Начислено 750 ₽LC';}},1000)}
  function usePromo(){var input=$('#promoInput'),code=(input&&input.value||'').trim().toUpperCase();if(!promo[code]){toast('Промокод не найден','bad');return}if(state.usedPromos.indexOf(code)>-1){toast('Код уже активирован','warn');return}state.usedPromos.push(code);earn(promo[code],'Промокод '+code);toast('Начислено '+fmt(promo[code]),'good')}
  function doUpgrade(){var u=$('#upItem'),t=$('#upTarget');if(!u||!t)return;var it=findInv(u.value),target=items.filter(function(x){return x.id===t.value})[0];if(!it||!target)return;var chance=Math.max(5,Math.min(75,Math.round((it.value/target.value)*82)));state.inventory=state.inventory.filter(function(x){return x.uid!==it.uid});if(rnd()*100<chance){addItem(target,'upgrade');toast('Апгрейд успешен','good')}else toast('Апгрейд проигран','bad');state.upgrades++;save();route()}
  function doContract(){var ids=state.contractSelected||[];if(ids.length<3||ids.length>10){toast('Нужно выбрать 3-10 предметов','warn');return}var sel=state.inventory.filter(function(x){return ids.indexOf(x.uid)>-1});var sum=sel.reduce(function(s,x){return s+x.value},0);state.inventory=state.inventory.filter(function(x){return ids.indexOf(x.uid)<0});state.contractSelected=[];var pool=items.filter(function(x){return x.value>=sum/ids.length*.9});addItem(pool[Math.floor(rnd()*pool.length)]||items[0],'contract');state.contracts++;save();route();toast('Контракт выполнен','good')}
  function startBattle(){var ca=findCase(($('#battleCase')||{}).value)||cases[0];if(!spend(ca.price,'Case Battle '+ca.name))return;var my=addItem(weighted(ca),'battle'),bot=weighted(ca),win=my.value>=bot.value;if(win){addItem(bot,'battle-win');state.wins++;toast('Ты победил в battle','good')}else{state.inventory=state.inventory.filter(function(x){return x.uid!==my.uid});toast('Ты проиграл battle','bad')}state.battles++;save();var a=$('#battleArena');if(a)a.innerHTML='<div class="grid cards-2"><div>'+itemCard(my,'')+'</div><div>'+itemCard(bot,'')+'</div></div><h2>'+(win?'Победа':'Поражение')+'</h2>';renderGlobals()}
  function toast(msg,type){var wrap=$('.toast-wrap');if(!wrap){wrap=document.createElement('div');wrap.className='toast-wrap';document.body.appendChild(wrap)}var d=document.createElement('div');d.className='toast '+(type||'');d.textContent=msg;wrap.appendChild(d);setTimeout(function(){d.parentNode&&d.parentNode.removeChild(d)},3500)}
  function wireActions(){var sel='button,a,[data-open-case],[data-view-case],[data-action],[data-sell],[data-close-modal],[data-contract-item],[data-upgrade-item]';$$(sel).forEach(function(el){if(el.__wired29)return;el.__wired29=1;var h=function(ev){var target=ev.currentTarget;if(action(target,ev))return;if(target.tagName==='A'&&target.getAttribute('href')){} };el.addEventListener('click',h,false);el.addEventListener('touchend',h,false);el.addEventListener('pointerup',function(ev){if(ev.pointerType==='touch')h(ev)},false)})}
  function initMenu(){var b=$('.menu-toggle'),back=$('.menu-backdrop');function close(){document.documentElement.classList.remove('nav-open');if(b)b.setAttribute('aria-expanded','false')}if(b)b.addEventListener('click',function(e){e.preventDefault();document.documentElement.classList.toggle('nav-open');b.setAttribute('aria-expanded',document.documentElement.classList.contains('nav-open')?'true':'false')});if(back)back.addEventListener('click',close);$$('.navlinks a').forEach(function(a){a.addEventListener('click',close)})}
  function boot(){try{for(var i=0;i<OLD_KEYS.length;i++)try{localStorage.removeItem(OLD_KEYS[i])}catch(e){} renderGlobals(); initMenu(); route(); setInterval(function(){renderGlobals()},3000);}catch(e){document.body.insertAdjacentHTML('beforeend','<div class="toast-wrap"><div class="toast bad">Ошибка запуска: '+esc(e.message)+'</div></div>')}}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();
